### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [nazlukyanovich/UI-Telegram-Web#1]
Looks good, need to make it a little bit better in terms of attention to details.
![image](https://user-images.githubusercontent.com/5592397/88589680-2e470480-d062-11ea-98d1-9a71af96ece8.png)

Thanks for the efforts and patience!
After fixes just put a comment here, we are monitoring the updates

**Comment by nazlukyanovich** [comment]
Thanks for your attention!
Bugs have been fixed

**Comment by ilya4321** [comment]
yeah, looks better, but still has issues 
![image](https://user-images.githubusercontent.com/5592397/88979369-35704b80-d2ca-11ea-971a-c7a0df28ff8d.png)

**Comment by nazlukyanovich** [comment]
fixed

**Comment by ilya4321** [comment]
Thanks, it's looking almost good! I still see an issue here
![image](https://user-images.githubusercontent.com/5592397/89210139-39e97c80-d5c8-11ea-9423-c34a21870fad.png)

**Comment by nazlukyanovich** [comment]
Thanks, fixed. I hope this was the last one

**Comment by ilya4321** [comment]
I still see an issue here
![image](https://user-images.githubusercontent.com/5592397/90012284-c58b9900-dcab-11ea-92ab-8ec7187ec366.png)

**Comment by nazlukyanovich** [comment]
fixed

**Comment by ilya4321** [comment]
Looks fine now, accepted
